version: "3.3"

services:
  database:
    image: postgres:alpine3.14
    environment:
      - "POSTGRES_PASSWORD=myexample"
      - "POSTGRES_USER=myexampleuser"
      - "POSTGRES_DB=listele"
    ports:
      - "6500:5432"
